# Generated by Django 6.0 on 2025-12-31 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quadra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('quadra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='core.quadra')),
            ],
            options={
                'unique_together': {('quadra', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='Gaveta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('status', models.CharField(choices=[('Livre', 'Livre'), ('Ocupado', 'Ocupado'), ('Vendido', 'Vendido')], default='Livre', max_length=20)),
                ('nome', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gavetas', to='core.lote')),
            ],
            options={
                'unique_together': {('lote', 'numero')},
            },
        ),
    ]
